# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

references:
  cache-key: &cache-key 'dishzero-npm:{{checksum "app/package-lock.json"}}'

commands:
  debug:
    steps:
      - run:
          command: pwd && ls -a
  checkout-app:
    steps:
      - checkout:
          path: /app
  restore-all:
    steps:
      - restore_cache:
          key: *cache-key


executors:
  ci-app:
      docker:
        - image: cimg/node:18.17.0
      resource_class: medium
      working_directory: /app

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  debug:
    executor: ci-app
    steps:
      - checkout
      - debug

  # install NPM dependencies
  dependencies:
    executor: ci-app
    steps:
      - checkout
      - restore-all
      - debug
      - run:
          name: "Install frontend dependencies"
          command: npm install --include dev
      - save_cache:
          paths: ["node_modules"]
          key: *cache-key


  # run eslint on frontend
  lint-app:
    executor: ci-app
    steps:
      - checkout
      - restore-all
      - debug
      - run:
          name: "Lint /app"
          command: npm run lint-ci

  test-app:
    executor: ci-app
    steps:
      - checkout
      - restore-all
      - debug
      - run:
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./test-results/
            JEST_JUNIT_ADD_FILE_ATTRIBUTE: "true"
          name: "Run tests"
          command: npm run test --coverage --reporters=default --reporters=jest-junit
      - run:
          command: ls -a
      - store_artifacts:
          path: /test-results/
      - store_test_results:
          path: /test-results/


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-test:
    jobs:
      - dependencies
      - lint-app:
          requires: [dependencies]
      - test-app:
          requires: [dependencies]
