# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

references:
  # the key used to pull npm dependencies from the cache
  cache-key: &cache-key 'dishzero-{{checksum "package-lock.json"}}'


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  dependencies:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - restore_cache:
          key: *cache-key
      - run:
          name: "Install NPM"
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: *cache-key

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-test:
    jobs:
      - dependencies
